"""initial_schema

Revision ID: 3a910914a186
Revises: 
Create Date: 2026-09-19 18:07:28.328517

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '3a910914a186'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('imoveis',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('finalidade', sa.String(length=20), nullable=False),
    sa.Column('operacao', sa.String(length=20), nullable=False),
    sa.Column('bairro', sa.String(length=100), nullable=False),
    sa.Column('zona', sa.String(length=50), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=False),
    sa.Column('estado', sa.String(length=2), nullable=False),
    sa.Column('preco', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('quartos', sa.SmallInteger(), nullable=False),
    sa.Column('suites', sa.SmallInteger(), nullable=True),
    sa.Column('banheiros', sa.SmallInteger(), nullable=True),
    sa.Column('vaga_garagem', sa.SmallInteger(), nullable=True),
    sa.Column('area_m2', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('condominio', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('iptu_anual', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('perfil_indicado', sa.String(length=30), nullable=True),
    sa.Column('disponivel', sa.Boolean(), nullable=False),
    sa.Column('imagem_url', sa.String(length=500), nullable=True),
    sa.Column('search_vector', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("finalidade IN ('residencial','comercial')", name='check_finalidade'),
    sa.CheckConstraint("operacao IN ('venda','aluguel')", name='check_operacao'),
    sa.CheckConstraint('area_m2 > 0', name='check_area'),
    sa.CheckConstraint('banheiros >= 0', name='check_banheiros'),
    sa.CheckConstraint('condominio >= 0', name='check_condominio'),
    sa.CheckConstraint('iptu_anual >= 0', name='check_iptu'),
    sa.CheckConstraint('preco > 0', name='check_preco'),
    sa.CheckConstraint('quartos >= 0', name='check_imovel_quartos'),
    sa.CheckConstraint('suites >= 0', name='check_suites'),
    sa.CheckConstraint('vaga_garagem >= 0', name='check_vagas'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leads',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=True),
    sa.Column('telefone', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('intencao', sa.String(length=30), nullable=True),
    sa.Column('tipologia_interesse', sa.String(length=30), nullable=True),
    sa.Column('orcamento_min', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('orcamento_max', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('forma_pagamento', sa.String(length=30), nullable=True),
    sa.Column('regiao_interesse', sa.String(length=80), nullable=True),
    sa.Column('bairro_interesse', sa.String(length=80), nullable=True),
    sa.Column('quartos', sa.SmallInteger(), nullable=True),
    sa.Column('urgencia', sa.String(length=20), nullable=True),
    sa.Column('motivo_busca', sa.String(length=120), nullable=True),
    sa.Column('perfil', sa.String(length=30), nullable=True),
    sa.Column('canal_origem', sa.String(length=30), nullable=True),
    sa.Column('amenidades_desejadas', sa.Text(), nullable=True),
    sa.Column('score', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('perfil_narrativo', sa.Text(), nullable=True),
    sa.Column('resumo', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("intencao IN ('compra','aluguel','investimento')", name='check_intencao'),
    sa.CheckConstraint("status IN ('novo','em_qualificacao','qualificado','agendado','inativo')", name='check_status'),
    sa.CheckConstraint("urgencia IN ('baixa','media','alta')", name='check_urgencia'),
    sa.CheckConstraint('orcamento_max >= 0', name='check_orcamento_max'),
    sa.CheckConstraint('orcamento_min >= 0', name='check_orcamento_min'),
    sa.CheckConstraint('quartos >= 0', name='check_quartos'),
    sa.CheckConstraint('score >= 0 AND score <= 10', name='check_score'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agendamentos',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('lead_id', sa.BigInteger(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('data_hora', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pendente','confirmado','cancelado','realizado')", name='check_status_agendamento'),
    sa.CheckConstraint("tipo IN ('visita','reuniao')", name='check_tipo_agendamento'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lead_channel_identities',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('lead_id', sa.BigInteger(), nullable=False),
    sa.Column('channel', sa.String(length=30), nullable=False),
    sa.Column('external_user_id', sa.String(length=100), nullable=True),
    sa.Column('external_chat_id', sa.String(length=100), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('llm_usage',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('lead_id', sa.BigInteger(), nullable=True),
    sa.Column('conversation_turn', sa.Integer(), nullable=True),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('tokens_input', sa.Integer(), nullable=False),
    sa.Column('tokens_output', sa.Integer(), nullable=False),
    sa.Column('tokens_total', sa.Integer(), nullable=False),
    sa.Column('estimated_cost_usd', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('operation', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('tokens_input >= 0', name='check_tokens_input'),
    sa.CheckConstraint('tokens_output >= 0', name='check_tokens_output'),
    sa.CheckConstraint('tokens_total >= 0', name='check_tokens_total'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mensagens',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('lead_id', sa.BigInteger(), nullable=False),
    sa.Column('channel', sa.String(length=30), nullable=False),
    sa.Column('channel_identity_id', sa.BigInteger(), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('message_type', sa.String(length=30), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('external_message_id', sa.String(length=100), nullable=True),
    sa.Column('in_reply_to_message_id', sa.BigInteger(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sent_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.CheckConstraint("message_type IN ('chat','followup','system_notice','handover')", name='check_message_type'),
    sa.CheckConstraint("role IN ('user','assistant','system','tool')", name='check_role'),
    sa.CheckConstraint("status IN ('created','received','generated','sent','failed')", name='check_msg_status'),
    sa.ForeignKeyConstraint(['in_reply_to_message_id'], ['mensagens.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('followup_attempts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('lead_id', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=True),
    sa.Column('regua', sa.String(length=30), nullable=False),
    sa.Column('attempt_number', sa.SmallInteger(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('failure_reason', sa.String(length=120), nullable=True),
    sa.Column('scheduled_for', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('executed_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("regua IN ('lead_novo_sem_resposta','qualificacao_interrompida','pos_envio_imoveis','pos_agendamento')", name='check_regua'),
    sa.CheckConstraint("status IN ('generated','sent','failed','skipped')", name='check_followup_status'),
    sa.CheckConstraint('attempt_number >= 1', name='check_attempt_number'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['mensagens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followup_attempts')
    op.drop_table('mensagens')
    op.drop_table('llm_usage')
    op.drop_table('lead_channel_identities')
    op.drop_table('agendamentos')
    op.drop_table('leads')
    op.drop_table('imoveis')
    # ### end Alembic commands ###
