"""unique_followup_attempt

Revision ID: d7b2eeb2efcf
Revises: 3a910914a186
Create Date: 2026-09-19 18:27:00.726127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd7b2eeb2efcf'
down_revision: Union[str, None] = '3a910914a186'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_followup_lead_regua_attempt', 'followup_attempts', ['lead_id', 'regua', 'attempt_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_followup_lead_regua_attempt', 'followup_attempts', type_='unique')
    # ### end Alembic commands ###
